"""Centralized defaults for self-play training/runtime."""

# PPO defaults
DEFAULT_GAMMA = 0.995
DEFAULT_GAE_LAMBDA = 0.95
DEFAULT_CLIP_EPSILON = 0.2
DEFAULT_VALUE_COEF = 0.5
DEFAULT_ENTROPY_COEF = 0.01
DEFAULT_ENTROPY_COEF_MIN = 0.001
DEFAULT_ENTROPY_ANNEAL_STEPS = 3_000_000
DEFAULT_LEARNING_RATE = 3e-4
DEFAULT_WEIGHT_DECAY = 1e-2
DEFAULT_GRAD_CLIP_NORM = 0.5
DEFAULT_PPO_EPOCHS = 4
DEFAULT_PPO_MINIBATCH_SIZE = 64
DEFAULT_KL_TARGET = 0.03
DEFAULT_KL_HARD_STOP = 0.08

# Model defaults
DEFAULT_STATIC_DIM = 128
DEFAULT_SEQUENCE_LEN = 240
DEFAULT_TOKEN_DIM = 8
DEFAULT_ACTION_DIM = 8
DEFAULT_UNIT_DIM = 128
DEFAULT_TURRET_DIM = 32
DEFAULT_SLOT_DIM = 4
DEFAULT_D_MODEL = 256
DEFAULT_N_HEADS = 8
DEFAULT_N_LAYERS = 8
DEFAULT_FFN_DIM = 1024
DEFAULT_DROPOUT = 0.1

# Runtime defaults
DEFAULT_SEED = 1337
DEFAULT_NUM_ENVS = 16
DEFAULT_ROLLOUT_HORIZON = 512
DEFAULT_TOTAL_STEPS = 10_000_000
DEFAULT_CHECKPOINT_EVERY = 100_000
DEFAULT_EVAL_EVERY = 200_000
DEFAULT_EVAL_MATCHES = 64
DEFAULT_EVAL_WORKERS = 64
DEFAULT_SAVE_DIR = "checkpoints"
DEFAULT_DEVICE = "cuda"
DEFAULT_MIXED_PRECISION = True

# Reward schedule defaults
DEFAULT_REWARD_NORMALIZE = True
DEFAULT_REWARD_CLIP_ABS = 10.0
DEFAULT_REWARD_DENSE_SCALE_START = 1.0
DEFAULT_REWARD_DENSE_SCALE_END = 1.0
DEFAULT_REWARD_DENSE_DECAY_INTERVAL = 0.2
DEFAULT_REWARD_DENSE_DECAY_FACTOR = 0.9
DEFAULT_REWARD_TERMINAL_SCALE_START = 1.0
DEFAULT_REWARD_TERMINAL_SCALE_END = 5.0
DEFAULT_REWARD_CURRICULUM_STEPS = 0
DEFAULT_REWARD_UNIT_CURRICULUM_END_PROGRESS = 0.2
DEFAULT_REWARD_UNIT_CURRICULUM_START_SCALE = 1.0
DEFAULT_REWARD_UNIT_CURRICULUM_END_SCALE = 0.0
DEFAULT_REWARD_DENSE_CUTOFF_PROGRESS = 0.6
DEFAULT_REWARD_KEEP_ENEMY_BASE_MILESTONE_AFTER_DENSE_CUTOFF = True

# League defaults
DEFAULT_LEAGUE_KEEP_TOP = 5
DEFAULT_LEAGUE_KEEP_DIVERSE = 5
DEFAULT_LEAGUE_MAX_AGENTS = 50  # learned agents; +5 fixed baseline opponents are always available
DEFAULT_LEAGUE_MIN_PROMOTE_WINRATE = 0.55
DEFAULT_LEAGUE_ARCHETYPE_WINRATE_FLOOR = 0.52
DEFAULT_LEAGUE_USE_CHECKPOINT_OPPONENTS = False
DEFAULT_LEAGUE_SPINOFFS_PER_ANCHOR = 0  # 0 => auto: max/(top+diverse)-1
DEFAULT_LEAGUE_SPINOFF_NOISE = 0.12
DEFAULT_LEAGUE_ARBITERS = "EASY,MEDIUM,HARD,SMART,CHEATER"
DEFAULT_LEAGUE_MIN_GAMES_PER_AGENT = 3
DEFAULT_LEAGUE_ELO_RANDOM_FACTOR = 0.15

# Dead-unit revival defaults
DEFAULT_DEAD_UNIT_REVIVAL_ENABLED = True
DEFAULT_DEAD_UNIT_CHECK_EVERY = 10
DEFAULT_DEAD_UNIT_ZERO_EPSILON = 1e-10
DEFAULT_DEAD_UNIT_STREAK = 50

# Logging/debug defaults
DEFAULT_LOG_INTERVAL = 2_048
DEFAULT_ENTROPY_FLOOR_ALERT = 0.003

# Smart env autoscale defaults
DEFAULT_SMART_ENV_AUTOSCALE = True
DEFAULT_SMART_ENV_TARGET_UTIL_PERCENT = 60.0
DEFAULT_SMART_ENV_SCALE_DOWN_TRIGGER_PERCENT = 90.0
DEFAULT_SMART_ENV_SCALE_STEP = 2
DEFAULT_SMART_ENV_ADJUST_COOLDOWN_SEC = 1.0
DEFAULT_SMART_ENV_MIN_ENVS = 32
DEFAULT_SMART_ENV_MAX_ENVS = 64  # 0 => unbounded
DEFAULT_SMART_ENV_SAMPLE_HZ = 10.0
DEFAULT_SMART_ENV_GPU_PROBE_HZ = 2.0
DEFAULT_SMART_ENV_GPU_SUSTAIN_SEC = 120.0

# Environment/bridge defaults
DEFAULT_ENV_BACKEND = "auto"
DEFAULT_OPPONENT_DIFFICULTY = "SMART_ML"
DEFAULT_SELF_DIFFICULTY = "SMART_ML"
DEFAULT_EPISODE_SECONDS = 3600
DEFAULT_DECISION_FRAMES = 30

# CLI behavior defaults
DEFAULT_MODEL_PRESET = "base"
DEFAULT_MILESTONE_FRACTIONS = "0.2,0.4,0.6,0.8,1.0"
DEFAULT_KEEP_AWAKE = True
DEFAULT_KEEP_AWAKE_INTERVAL_SEC = 600.0
DEFAULT_EXPORT_REGISTRY = True
DEFAULT_CLEAN_RUN = True

# Preset overrides for model architecture
MODEL_PRESET_OVERRIDES = {
    "tiny": {
        "d_model": 128,
        "n_layers": 4,
        "n_heads": 4,
        "ffn_dim": 384,
        "sequence_len": 160,
        "dropout": 0.05,
    },
    "medium": {
        "d_model": 224,
        "n_layers": 7,
        "n_heads": 7,
        "ffn_dim": 896,
        "sequence_len": 240,
        "dropout": 0.08,
    },
    "medium-large": {
        "d_model": 288,
        "n_layers": 9,
        "n_heads": 9,
        "ffn_dim": 1152,
        "sequence_len": 240,
        "dropout": 0.1,
    },
    "large": {
        "d_model": 320,
        "n_layers": 10,
        "n_heads": 10,
        "ffn_dim": 1280,
        "sequence_len": 240,
        "dropout": 0.1,
    },
    "extra-large": {
        "d_model": 384,
        "n_layers": 12,
        "n_heads": 12,
        "ffn_dim": 1536,
        "sequence_len": 240,
        "dropout": 0.12,
    },
    "humangous": {
        "d_model": 448,
        "n_layers": 14,
        "n_heads": 14,
        "ffn_dim": 1792,
        "sequence_len": 240,
        "dropout": 0.15,
    },
}
